### ISSUE TITLE
 source .envrc  --> Connection to server closed.

### ISSUE THREAD

**Issue by patsevanton** [hnakamur/clickhouse-rpm#1]
Hello!
I try import CORP credentials
login = ..............
username = antonpatsev
token = ................
copr_url = https://copr.fedorainfracloud.org

[root@fedora26 ~]# source .envrc 
Connection to fedora26.paa closed.

What is format  .envrc ?
Thank you

**Comment by hnakamur** [comment]
Ah, sorry, I had forgotten to add `.envrc.example`.
Added it at https://github.com/hnakamur/clickhouse-rpm/pull/2

The format of .envrc is:

```
# NOTE: Copy this file to .envrc and edit the values
# Go https://copr.fedoraproject.org/api/ and login in and see the values to set.
export COPR_LOGIN=_your_login_here_
export COPR_USERNAME=_your_username_here_
export COPR_TOKEN=_your_token_here_
```

**Comment by patsevanton** [comment]
Thank you
